// <auto-generated />
namespace ItLab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangesToId3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangesToId3));
        
        string IMigrationMetadata.Id
        {
            get { return "201804241605507_ChangesToId3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
